# Ch02_Hello, Python

## Expressions and Values: Arithmetic in Python, p. 9

###### Expression, Operator, Operand, Mathematical Expression, 

In [1]:
# Operators and operands
# Operators: +, -, *, /, //, %, and **
# operands: 2, 3, 5
2 - 3 / 5

1.4

In [2]:
# The following expression adds 2 and 10:
print(2 + 10)
2 + 10

12


12

In [3]:
print(2 + 10)
print(2 + 10)

12
12


In [4]:
# Python can evaluate basic mathematical expressions
2 + 10

12

The >>> symbol is called a prompt.

A number by itself is an expression.
The number 354 is an expression as well as a value.

In [5]:
5/2

2.5

In [6]:
4 / 2

2.0

In [1]:
4 * 2

8

In [4]:
4 + 2.0 + 5

11.0

### Types, p. 10
1. two types of numbers (integers and floating-point numbers)
    + integer: 4, 6, ...
    + float (floating point number): 3.2, 55.6, ...

In [1]:
# The operation on two floats produces a float. 
15.0 - 8.0

7.0

In [2]:
# The operation on one integer and the other float gets a float.
15.0 - 8

7.0

In [3]:
15 - 8.0

7.0

In [4]:
15 - 8.

7.0

In [5]:
15. - 8

7.0

### Integer Division (//), Modulo (%), and Exponentiation (**), p. 11

In [13]:
# Integer division takes the floor. It rounds down to the nearest integer.
# Integer division is also called floor division.
53 // 5     #取整數商

10

In [32]:
# Integer division takes the floor. It rounds down to the nearest integer.
# Integer division is also called floor division.
5//3

1

In [31]:
# Integer division takes the floor. It rounds down to the nearest integer.
# Integer division is also called floor division.
2//3

0

In [14]:
# Modulo operator (%) gives the remainder of the division.
58 % 5

3

In [33]:
# Modulo operator (%) gives the remainder of the division.
3 % 2

1

In [34]:
# Modulo operator (%) gives the remainder of the division.
4 % 2

0

In [5]:
# Exponentiation operator
2**3    #次方

8

Q. When applied to two int operands, which operation always evaluates to type float?

1. multiplication
2. division  (整數相除會變小數點)
3. integer division (or floor division)
4. exponentiation
5. modulo (remainder)

### math.floor(x) returns the largest integer value less than or equal to x

In [8]:
import math
dir(math)
help(math.floor)

Help on built-in function floor in module math:

floor(x, /)
    Return the floor of x as an Integral.
    
    This is the largest integer <= x.



In [10]:
# Check if these data types in module builtins: 
# int, float, complex, str, bool, list, tuple, dict, set, range, etc.
import builtins
print(dir(builtins))
# help(builtins.help)

['ArithmeticError', 'AssertionError', 'AttributeError', 'BaseException', 'BlockingIOError', 'BrokenPipeError', 'BufferError', 'BytesWarning', 'ChildProcessError', 'ConnectionAbortedError', 'ConnectionError', 'ConnectionRefusedError', 'ConnectionResetError', 'DeprecationWarning', 'EOFError', 'Ellipsis', 'EnvironmentError', 'Exception', 'False', 'FileExistsError', 'FileNotFoundError', 'FloatingPointError', 'FutureWarning', 'GeneratorExit', 'IOError', 'ImportError', 'ImportWarning', 'IndentationError', 'IndexError', 'InterruptedError', 'IsADirectoryError', 'KeyError', 'KeyboardInterrupt', 'LookupError', 'MemoryError', 'ModuleNotFoundError', 'NameError', 'None', 'NotADirectoryError', 'NotImplemented', 'NotImplementedError', 'OSError', 'OverflowError', 'PendingDeprecationWarning', 'PermissionError', 'ProcessLookupError', 'RecursionError', 'ReferenceError', 'ResourceWarning', 'RuntimeError', 'RuntimeWarning', 'StopAsyncIteration', 'StopIteration', 'SyntaxError', 'SyntaxWarning', 'SystemError

In [12]:
# dir(builtins.list) & dir(list) get the same result.
# dir(builtins.list)
# dir(list)

In [5]:
# math.floor (x) returns the floor of x as a float, 下一個整數
#　the largest integer value less than or equal to x. 
import math
print(math.floor(3.333))
print(math.floor(3.7))
print(math.floor(-3.333))
print(math.floor(-3.7))

3
3
-4
-4


In [11]:
5 % 3

2

### % and // with negative operands, p. 11

1. Source: [Integer division & modulo operation with negative operands in Python
](https://stackoverflow.com/questions/14348219/integer-division-modulo-operation-with-negative-operands-in-python)

2. For integer division & modulo operation with negative operands in Python
    + a // b = floor(a / b)   取下一個整數
    + a % b = a - floor(a / b) * b 

3. Python takes the floor of the result of an integer division.
    + -10 // 3        # -4     
        + a // b = floor(a/b) = floor(-10/3) = floor(-3.333…) = -4
    + -10// -3        #  3     
        + a // b = floor(a/b) = floor(-10/-3) = floor(3.333…) = 3
    + 10 // -3        # -4     
        + a // b = floor(a/b) = floor(10/-3) = floor(-3.333…) = -4 
    + -10 % 3         #  2     
        + a % b = a - floor(a / b)*b = -10 – floor(-10/3)*3= -10-(-12)= 2 
    + 10 % -3         # -2     
        + a % b = a - floor(a / b)*b =10–floor(10/-3)*(-3)=10-(12)= -2

In [11]:
-10 // 3

-4

In [1]:
-10 / 3

-3.3333333333333335

In [2]:
-10 // 3

-4

In [4]:
# Both are equivalent.
print(-10 // 3)

import math
math.floor(-10 / 3)

-4


-4

In [16]:
-17 // 10

-2

In [17]:
-10 // -3

3

In [18]:
10 // -3

-4

In [3]:
10 % 3

1

In [5]:
# a-floor(a/b)*b = (-10) - (-4)*(3) = 2
-10 % 3 

2

In [6]:
# -10 % 3: a-math.floor(a/b)*b 
import math
(-10)-math.floor(-10/3)*3

2

In [6]:
# a-floor(a/b)*b = 10 - (-4)*(-3) = -2
10 % -3

-2

In [7]:
# -10 % 3: a-math.floor(a/b)*b 
import math
(10)-math.floor(10/-3)*(-3)

-2

###### Exercises 
1. 3.3 // 1
2.   3 // 1.0
3.   3 // 1.1
4. 3.5 // 1.1
5. 3.5 // 1.3

6.  -10 % 4
7.  -17 % 5
8.  -10 % -4
9.   10 % -4
10. -10 % 4 

In [21]:
# binary operators: Operators that have two operands are called binary operators. 
# For example, 5 * 4 

# unary operator: Negation is a unary operator because it applies to one operand:
# Examples of unary operator:

# -5     # -5  
# --5    #  5
# ---5   # -5

### What Is a Type? p. 12
+ Two types of numbers: 
    1. integers 
    2. floating-point numbers
+ For numbers, type consists of two things: 
    1. A set of values 
    2. A set of operations that can be applied to those values
+ For example: In type int
    1. values: -3, -2, -1, 0, 1, 2, 3, … 
    2. operators: +, -, *, /, //, %, and **
+ If an operator can be applied to more than one type of value, it is called an overloaded operator.

### Finite Precision, p. 12

###### Why the value of 2/3 ends with a 6 while the 5/3 with a 7?
+ The problem is that computers have **a finite amount of memory**, and (to make calculations fast and memory efficient) most programming languages **limit how much information can be stored** for any single number. The number 0.6666666666666666 turns out to be the closest value to 2⁄3 that the computer can actually store in that limited amount of memory, and 1.6666666666666667 is as close as we get to the real value of 5⁄3.

In [8]:
print(2/3)
print(5/3)

0.6666666666666666
1.6666666666666667


### Operator Precedence, p. 13
+ converting Fahrenheit to Celsius

In [24]:
# converting Fahrenheit to Celsius
(212 - 32) * 5 / 9

100.0

### More on Numeric Precision, p. 13
1. The rounding error may get compounded so that in many programming languages, 1 + 2⁄3 is not equal to 5⁄3:

In [9]:
# Rounding error: 1 + 2⁄3 is not equal to 5⁄3
print(5 / 3)
print(2 / 3 + 1)

1.6666666666666667
1.6666666666666665


### More on Numeric Precision (cont'd), p. 13
2. As we do more calculations, the rounding errors can get larger and larger, particularly if we’re mixing very large and very small numbers.

In [27]:
# The calculaiton below has too many zeros for the computer to store, 
# so the result is just 10000000000—it’s as if the addition never took place. 
# Adding lots of small numbers to a large one can therefore have no effect 
# at all, which is not what a bank wants.

10000000000  +  0.00000000001

10000000000.0

###### The floating-point issue, p. 13
###### Here’s a tip: If you have to add up floating-point numbers, add them from smallest to largest in order to minimize the error.

##### Precedence from Highest to Lowest for Arithmetic Operators

###### Exponentiation has higher precedence than negation

In [28]:
# Since exponentiation has higher precedence than negation, 
# the subexpression 2 ** 4 is evaluated before negation is applied: 

-2 ** 4    # same as -(2 ** 4)

-16

In [29]:
-(2 ** 4)  # -16

-16

In [30]:
(-2) ** 4  # 16

16

## Variables and Computer Memory: Remembering Values, p. 15
1. Variable: name of a value
2. Variable names can use **letters, digits, and the underscore symbol (but they can’t start with a digit):**
    + variable
    + variable1
    + variable_2
    + _varaible
    + _2
    + 2_variable is not an acceptable varaible name

In [13]:
_x = 5
_2 = 4
print(_x)
print(_2)

5
4


In [12]:
# Creating a new variable by assigning it a value:
# This statement is called an assignment statement;  
# we say that degrees_celsius is assigned the value 26.0.

degrees_celsius = 26.0 # assignment: degrees_celsius is assigned the value 26.0
print(degrees_celsius)
degrees_celsius

26.0


26.0

In [33]:
# Variables are called variables because their values can vary as the program 
# executes. 
# We can assign a new value to a variable:

degrees_celsius = 26.0
print(9 / 5 * degrees_celsius + 32)    # 78.80000000000001

degrees_celsius = 0.0           # re-assign 0 to the variable degrees_celsius 
print(9 / 5 * degrees_celsius + 32)    # 32.0

78.80000000000001
32.0


In [33]:
# The temperature stored in degrees_celsius:
degrees_celsius = 15.5
difference = 100 - degrees_celsius
difference

84.5

###### Warning: = Is Not Equality in Python!
+ We read "x = 12" as “x gets 12” or “x is assigned 12.”

### Values, Variables, and Computer Memory, p. 16

[The Python Visualizer](http://pythontutor.com/visualize.html)

In [42]:
x = 8
y = x + 12
x = 5
print(x)

In [ ]:
degrees_celsius  =  26.0  

###### Memory model, p. 17
1. memory address: id1, id2, id3, and so on
2. Memory model: 
    + **Value** 26.0 **has** the **memory address** id1.
    + The **object** at the **memory address id1** has **type** float and the **value** 26.0.
    + **Variable** degrees_celsius **contains** the **memory address** id1.
    + **Variable** degrees_celsius **refers** to the **value** 26.0.
    + **Variable** degrees_celsius **points** to the **value** 26.0.
3. Summary:
    + **Values**
    + **Memory address, id1, id2, etc.**
    + **Object at memory address id1** 
    + **Object has type and value**
    + **Variables**    

### Assignment  Statement, p. 18

1. The general form of an assignment statement:
    + **«variable» =  «expression»**

2. This is executed as follows:
    + **Evaluate** the expression on the **right** of the = sign to produce a **value**. This **value has a memory address**.
    + **Store the memory address of the value in the variable** on the **left** of the =.
Create a new variable if that name doesn’t already exist; otherwise, just reuse the existing variable, replacing the memory address that it contains.


In [34]:
degrees_celsius  =  26.0  +  5
degrees_celsius

31.0

###### Here is how Python executes the statement degrees_celsius = 26.0 + 5:
1. Evaluate the expression on the right of the = sign: 26.0 + 5. This produces the **value** 31.0, which **has** a **memory address**. (Remember that Python stores all values in computer memory.)
2. Make the **variable** on the left of the = sign, degrees_celsius, **refer to** 31.0 **by storing the memory address of 31.0 in degrees_celsius**.

In [ ]:
X = 26.0
The value 26.0 has memory address id1.
The variable X contains memory address id1.
The memory address is stored in the varible X.
The variable X refers to the value 26.0.
The variable X gets the value 26.0.
The variable X is assigned the value 26.0. 
The object at the memory address id1 has the floating point type and value 26.0.
The variable X refers to value 26.0 by storing the memory address id1 of 26.0 in X.

### Reassigning to Variables

In [12]:
difference  =  20
double = 2 * difference
print(double)             # 40

difference  =  5
print(difference)
double                    # 40

40
5


40

###### We can even use a variable on both sides of an assignment statement: (p. 20)

In [36]:
number = 3
number                   # 3

3

In [37]:
number = 3
number = 2 * number
number                   # 6

6

In [38]:
number = number * number
number                   # 36

36

### Augmented Assignment, p. 21
1. Augmented Assignment: score += 20; score -= 20; score *= 20; score /= 20
2. Two calculations below are equivalent:
    + score = score + 20
    + score += 20 

In [15]:
score = 50
score = score + 20
score

70

In [17]:
# same as the above
score = 50
score += 20     # same as: score = score + 20
score

70

In [4]:
score = 50
score -= 20 
score

30

In [5]:
score = 50
score *= 20 
score

1000

In [43]:
score = 50
score /= 20 
score

2.5

In [7]:
number  =  10
number  *=  number    # equivalent to: number = number * number
number

100

In [6]:
x = 7
x //= 2   # equivalent to: x = x // 2
x

3

In [8]:
x = 7
x %= 2
x

1

In [9]:
x = 7
x **= 2
x

49

## How Python Tells You Something Went Wrong, p. 22
1. Two kinds of errors in Python: 
    + **syntax errors** which happen when you type something that isn’t valid Python code
    + **semantic errors** which happen when you tell Python to do something that it just can’t do, like **dividing a number by zero** or try to **use a variable that doesn’t exist**.

In [18]:
# Semantic Error: this example uses a variable that doesn't exit
3 + moogah

NameError: name 'moogah' is not defined

In [20]:
# Semantic Error: division by zero
5 / 0

ZeroDivisionError: division by zero

In [19]:
# Syntax Error
2 + 

SyntaxError: invalid syntax (<ipython-input-19-d384b8179747>, line 2)

In [21]:
# Syntax Error
**

SyntaxError: invalid syntax (<ipython-input-21-5985565381b4>, line 2)

In [22]:
# Syntax Error
3 + (8 *

SyntaxError: unexpected EOF while parsing (<ipython-input-22-f98d4777fbd3>, line 2)

In [23]:
# Syntax Error: can't assign to literal like 12 or 26.0.
# Note that a literal is any value, like 12 and 26.0.
12 = x

SyntaxError: can't assign to literal (<ipython-input-23-bc9435e8cdba>, line 3)

In [24]:
# Syntax Error: can't assign to literal
12 = 12

SyntaxError: can't assign to literal (<ipython-input-24-b8116568c53e>, line 2)

Q. Which one results in a SyntaxError?
1. 5 **
2. 3 + -5
3. (8 / (10 / (4 / 2))
4. (3 + 2) * 5  

### A Single Statement That Spans Multiple Lines, p. 23
In order to split up a statement into more than one line, you need to do one of two things:
1.	Make sure your line break occurs inside parentheses.
2.	Use the line-continuation character, which is a backslash, '\\'.

In [29]:
# SyntaxError (Make sure your line break occurs inside parentheses)
2 + 
  3

SyntaxError: invalid syntax (<ipython-input-29-d0f300186077>, line 2)

In [25]:
# vaild 
(2 + 
  3)

5

In [30]:
# valid
# \: line-continuation character
2 + \
3

5

In [33]:
# invalid
# \: line-continuation character
2 + \   
3

SyntaxError: unexpected character after line continuation character (<ipython-input-33-63c863f1631e>, line 3)

In [33]:
# SyntaxError 
2 + 
3 

SyntaxError: invalid syntax (<ipython-input-33-2c90adf8e5c6>, line 2)

In [32]:
# valid
2 + \
3 

5

In [31]:
# invalid
2 + \   
3 

SyntaxError: unexpected character after line continuation character (<ipython-input-31-cd9e8393cb00>, line 2)

In [40]:
# Good example 1
room_temperature_c  =  20
cooking_temperature_f  =  350
oven_heating_rate_c  =  20
oven_heating_time = (
    ((cooking_temperature_f - 32) * 5 / 9) -
    room_temperature_c) / \
    oven_heating_rate_c
oven_heating_time

7.833333333333333

In [41]:
# Good example 2
room_temperature_c  =  20
cooking_temperature_f  =  350
oven_heating_rate_c  =  20
oven_heating_time = (
((cooking_temperature_f - 32) * 5 / 9) - room_temperature_c) / \
oven_heating_rate_c
oven_heating_time

7.833333333333333

In [26]:
# invalid
x = 20 / \  
    4
x

SyntaxError: unexpected character after line continuation character (<ipython-input-26-a7e27a7bb4c3>, line 1)

In [10]:
# valid
x = 20 / \
    4
x

5.0

### Describing Code, p. 25
1. #: comments
2. comment describing your code

In [27]:
# Convert 212 degrees Fahrenheit to Celsius.
(212 - 32) * 5 / 9 

100.0

In [59]:
(212 - 32) * 5 / 9 # Convert 212 degrees Fahrenheit to Celsius.

100.0

### Making Code Readable, p. 26
1. **Meaningful variable names** like celsius, average, and final_result
2. **Consistent names for variables:** if you use the name max_val, then don’t also use the name maxVal
3. **Spaces** make code more readable: always put a space before and after every binary operator, such as x = 2 + 3
4. PEP 8 -- Style Guide for Python Code: https://www.python.org/dev/peps/pep-0008/#blank-lines

In [28]:
# Bad coding: no spaces
v=4+-2.5/3.6
v

3.3055555555555554

In [29]:
# Good coding: using spaces
v = 4 + -2.5 / 3.6
v

3.3055555555555554

## The End!